### 🔍 DATA DETECTIVE CHALLENGE: Patient Records Investigation

 Your mission: Clean and analyze this messy patient records dataset!

 SCORING SYSTEM:
 - Each bug found and fixed: 5 points
 - Bonus: Creative solution: +3 points
 - Speed bonus: First to finish correctly: +10 points

 Total possible bugs: 15+ categories
 Maximum score: 100+ points

In [362]:
import pandas as pd
import numpy as np
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

In [363]:
# ================================================================
# STEP 1: LOAD THE DATA
# ================================================================

# TODO: Load the messy_patient_records.csv file
df = pd.read_csv('messy_patient_records.csv')

print("Dataset loaded successfully!")
print(f"Shape: {df.shape}")
print("\n" + "="*70)

Dataset loaded successfully!
Shape: (100, 15)

======================================================================

In [364]:
# ================================================================
# STEP 2: INITIAL EXPLORATION
# ================================================================
# Get a feel for the data before you start cleaning

print("\n🔎 INITIAL DATA INSPECTION")
print("="*70)

# Display data types
print("\n📊 Data Types:")
print(df.dtypes)

# Display basic info
print("\n📋 Dataset Info:")
print(df.info())

# Check for missing values
print("\n❓ Missing Values Count:")
print(df.isnull().sum())
print(df.isna().sum())

print("\n" + "="*70)

🔎 INITIAL DATA INSPECTION
======================================================================

📊 Data Types:
Patient_ID            float64
First_Name             object
Last_Name              object
Date_of_Birth          object
Age                   float64
Gender                 object
Blood_Type             object
Admission_Date         object
Discharge_Date         object
Diagnosis              object
Temperature            object
Blood_Pressure         object
Heart_Rate            float64
Insurance_Provider     object
Bill_Amount            object
dtype: object

📋 Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          98 non-null     float64
 1   First_Name          98 non-null     object
 2   Last_Name           98 non-null     object
 3   Date_of_Birth       82 non-null     object
 4   Age                 95 non-null     float64
 5   Gender              97 non-null     object
 6   Blood_Type          98 non-null     object
 7   Admission_Date      90 non-null     object
 8   Discharge_Date      81 non-null     object
 9   Diagnosis           100 non-null    object
 10  Temperature         96 non-null     object
 11  Blood_Pressure      97 non-null     object
 12  Heart_Rate          98 non-null     float64
 13  Insurance_Provider  88 non-null     object
 14  Bill_Amount         97 non-null     object
dtypes: float64(3), object(12)
memory usage: 11.8+ KB
None

❓ Missing Values Count:
Patient_ID             2
First_Name             2
Last_Name              2
Date_of_Birth         18
Age                    5
Gender                 3
Blood_Type             2
Admission_Date        10
Discharge_Date        19
Diagnosis              0
Temperature            4
Blood_Pressure         3
Heart_Rate             2
Insurance_Provider    12
Bill_Amount            3
dtype: int64
Patient_ID             2
First_Name             2
Last_Name              2
Date_of_Birth         18
Age                    5
Gender                 3
Blood_Type             2
Admission_Date        10
Discharge_Date        19
Diagnosis              0
Temperature            4
Blood_Pressure         3
Heart_Rate             2
Insurance_Provider    12
Bill_Amount            3
dtype: int64

======================================================================

In [365]:
# Display first few rows
print("\nFirst 10 rows:")
df.head(10)

First 10 rows:

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001.0,John,Smith,NaN,45.0,Unknown,A +,2024/10/15,NaN,Flu,97.3F,151 / 88,78.0,NaN,$566
1,1002.0,Mary,johnson,1954-01-24,26.0,MALE,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003.0,james,WILLIAMS,1975-04-08,34.0,M,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78.0,BlueCross,7015.1
3,1004.0,SARAH,Brown,1957-12-04,34.0,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88.0,BLUECROSS,7574.35
4,1005.0,Michael,Jones,2009-02-19,78.0,MALE,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,UnitedHealth,965.92
5,1006.0,Robert,Garcia,1994-01-01,39.0,M,B+,2025-05-05,2025-05-18,Migraine,37.8,152/64,67.0,BLUECROSS,6260.86
6,1007.0,william,Miller,1951-04-08,51.0,MALE,A+,2025-03-13,2025-03-21,Anxiety,37.6,163/100,61.0,blue cross,5218.91
7,1008.0,Olivia,Davis,NaN,85.0,m,O+,2024-12-30,2025-01-09,Bronchitis,39.2,177/63,100.0,Cigna,9089.48
8,1009.0,David,NaN,2004-10-01,72.0,FEMALE,O-,2025-10-06,2025-10-01,Fracture,37.9,109/69,98.0,aetna,3218.84
9,1010.0,Sophia,Martinez,2011-04-23,45.0,m,A+,NaN,NaN,Bronchitis,37.0,162 / 120,75.0,United Health,8089.17

In [366]:
# ================================================================
# 🎯 CLUES: Types of Bugs Hidden in the Dataset
# ================================================================
print("\n🕵️ DETECTIVE CLUES - Types of bugs you'll find:")
print("="*70)
print("""
1. 🔢 DUPLICATE DATA: Some patients appear more than once
2. ❌ MISSING VALUES: Multiple types (None, NaN, 'NA', 'N/A', empty strings)
3. 🔤 DATA TYPE ISSUES: Numbers stored as strings, dates as objects
4. 📅 DATE FORMAT ISSUES: Inconsistent date formats across columns
5. 🎨 FORMATTING ISSUES: Extra whitespace, inconsistent capitalization
6. 🚫 INVALID VALUES: Impossible ages, negative numbers where they shouldn't be
7. 🌡️ MIXED UNITS: Temperature in different units (Celsius vs Fahrenheit)
8. 🩸 TYPOS: Misspellings in categorical data
9. ⚖️ INCONSISTENT NAMING: Same values written differently
10. 🔀 LOGICAL INCONSISTENCIES: Dates that don't make sense (discharge before admission)
11. 📊 OUTLIERS: Values way outside normal ranges
12. 🔢 WRONG SEPARATORS: Data formatted incorrectly
13. 💵 CURRENCY SYMBOLS: Embedded in numeric data
14. 🎭 CATEGORICAL CHAOS: Same categories with different cases/formats
15. 🔄 INCONSISTENT NULLS: Different representations of missing data

Your challenge: Find and fix ALL of them!
""")
print("="*70)

🕵️ DETECTIVE CLUES - Types of bugs you'll find:
======================================================================

1. 🔢 DUPLICATE DATA: Some patients appear more than once
2. ❌ MISSING VALUES: Multiple types (None, NaN, 'NA', 'N/A', empty strings)
3. 🔤 DATA TYPE ISSUES: Numbers stored as strings, dates as objects
4. 📅 DATE FORMAT ISSUES: Inconsistent date formats across columns
5. 🎨 FORMATTING ISSUES: Extra whitespace, inconsistent capitalization
6. 🚫 INVALID VALUES: Impossible ages, negative numbers where they shouldn't be
7. 🌡️ MIXED UNITS: Temperature in different units (Celsius vs Fahrenheit)
8. 🩸 TYPOS: Misspellings in categorical data
9. ⚖️ INCONSISTENT NAMING: Same values written differently
10. 🔀 LOGICAL INCONSISTENCIES: Dates that don't make sense (discharge before admission)
11. 📊 OUTLIERS: Values way outside normal ranges
12. 🔢 WRONG SEPARATORS: Data formatted incorrectly
13. 💵 CURRENCY SYMBOLS: Embedded in numeric data
14. 🎭 CATEGORICAL CHAOS: Same categories with different cases/formats
15. 🔄 INCONSISTENT NULLS: Different representations of missing data

Your challenge: Find and fix ALL of them!

======================================================================

In [367]:
# ================================================================
# STEP 3: START YOUR INVESTIGATION
# ================================================================

# Create a copy to work with (always keep original!)
df_clean = df.copy()

print("\n🧹 CLEANING PROCESS BEGINS!")
print("="*70)

🧹 CLEANING PROCESS BEGINS!
======================================================================

In [368]:
# ----------------------------------------------------------------
# BUG CATEGORY 1: DUPLICATE RECORDS
# ----------------------------------------------------------------
print("\n1️⃣ Checking for duplicates...")

# TODO: Check for duplicate Patient_IDs
# HINT: Use df_clean['Patient_ID'].duplicated()
#print the rows with repeating data
print(df_clean[df_clean['Patient_ID'].duplicated()])

#correct Patient_ids
df_clean["Patient_ID"]= range(1001, 1001+len(df_clean))
df_clean

#ckeck to see if you still have duplicates in Patient IDs
print(df_clean[df_clean['Patient_ID'].duplicated()])

#check for duplicate names

df_clean.duplicated(subset=['First_Name', 'Last_Name'], keep = False).value_counts()
df_clean[df_clean.duplicated(subset=['First_Name', 'Last_Name'], keep = False)].sort_values(['First_Name','Last_Name'])
# at this level data presents duplicate entries in names but different DOB
#we are going to check which entries actually have similar/different DOB and group them
#any name with a UniqueDOB > 1 means occurs with multiple date of births
DOB_check=df_clean.groupby(['First_Name', 'Last_Name'])['Date_of_Birth'].nunique().reset_index(name='UniqueDOB')
print(DOB_check)

# TODO: Remove or handle duplicates
# HINT: Use drop_duplicates() or investigate why duplicates exist


#print("✓ Duplicate check complete")

1️⃣ Checking for duplicates...
    Patient_ID First_Name Last_Name Date_of_Birth   Age Gender Blood_Type  \
14      1015.0  Michael       Jones           NaN  65.0      m         A-
25      1015.0       Emma    Garcia    2008-02-13  61.0   Male        XY+
75         NaN       Emma    Garcia    1985/05/20  75.0      m        XY+

   Admission_Date Discharge_Date Diagnosis Temperature Blood_Pressure  \
14     2024/10/15     2024-10-22  COVID-19        39.3        166/110
25     2024-10-26     2024-11-03   Anxiety        37.3         117/76
75     2024-11-05     2024-11-11    ASTHMA        37.1         152-65

    Heart_Rate Insurance_Provider Bill_Amount
14        60.0              CIGNA       $1620
25        69.0              aetna         NaN
75        75.0      United Health         NaN
Empty DataFrame
Columns: [Patient_ID, First_Name, Last_Name, Date_of_Birth, Age, Gender, Blood_Type, Admission_Date, Discharge_Date, Diagnosis, Temperature, Blood_Pressure, Heart_Rate, Insurance_Provider, Bill_Amount]
Index: []
   First_Name  Last_Name  UniqueDOB
0      Robert     Garcia          1
1       David  rodriguez          7
2     David    rodriguez          0
3        Emma     Garcia          6
4      Emma       Garcia          0
5        John      Smith          3
6      John        Smith          0
7        Mary    johnson          8
8      Mary      johnson          0
9     Michael      Jones          8
10  Michael        Jones          0
11     Olivia      Davis          8
12   Olivia        Davis          1
13      SARAH      Brown          9
14    SARAH        Brown          0
15     Sophia   Martinez          9
16   Sophia     Martinez          0
17      james   WILLIAMS          8
18    james     WILLIAMS          0
19    william     Miller          9
20  william       Miller          0

In [369]:
# ----------------------------------------------------------------
# BUG CATEGORY 2: MISSING VALUES - STANDARDIZE
# ----------------------------------------------------------------
print("\n2️⃣ Standardizing missing values...")

# TODO: Replace all variations of missing values with proper NaN
# HINT: Look for 'NA', 'N/A', empty strings '', and convert to np.nan
# HINT: Use replace() method
#replacing all posible instances of missing data
df_clean.replace(['', ' ', 'NA', 'N/A', 'n/a', 'null', 'NULL', '-'],pd.NA, inplace=True)
df_clean



#print("✓ Missing values standardized")

2️⃣ Standardizing missing values...

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,NaN,45.0,Unknown,A +,2024/10/15,NaN,Flu,97.3F,151 / 88,78.0,NaN,$566
1,1002,Mary,johnson,1954-01-24,26.0,MALE,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003,james,WILLIAMS,1975-04-08,34.0,M,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78.0,BlueCross,7015.1
3,1004,SARAH,Brown,1957-12-04,34.0,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88.0,BLUECROSS,7574.35
4,1005,Michael,Jones,2009-02-19,78.0,MALE,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,UnitedHealth,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,NaN,MALE,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66.0,NaN,4712.14
96,1097,william,Miller,1970-10-03,70.0,M,A +,2025-11-06,2025-11-01,Flu,NaN,153/100,78.0,NaN,9530.27
97,1098,Olivia,Davis,1950-12-16,80.0,F,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88.0,BlueCross,8626.78
98,1099,David,rodriguez,NaN,79.0,F,AB+,2024/10/15,2024-10-16,COVID-19,36.5,96/73,66.0,UnitedHealth,$1313
99,1100,Sophia,Martinez,15-08-1990,45.0,Male,AB+,NaN,NaN,Flu,37.4,124 / 95,93.0,aetna,9818.81

In [370]:
# ----------------------------------------------------------------
# BUG CATEGORY 3: WHITESPACE ISSUES
# ----------------------------------------------------------------
print("\n3️⃣ Cleaning whitespace...")

# TODO: Remove leading/trailing whitespace from text columns
# HINT: Use .str.strip() on string columns
#cleaning can be done per column or for the entire dataset
#per colum route example
    #df_clean['First_Name'] = df_clean['First_Name'].str.strip()
#taking the entire dataset route
df_clean = df_clean.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)
print(df_clean)
# also the column names
df_clean.columns = df_clean.columns.str.strip()
print("✓ Whitespace cleaned")

3️⃣ Cleaning whitespace...
    Patient_ID First_Name  Last_Name Date_of_Birth   Age   Gender Blood_Type  \
0         1001       John      Smith           NaN  45.0  Unknown        A +
1         1002       Mary    johnson    1954-01-24  26.0     MALE         A+
2         1003      james   WILLIAMS    1975-04-08  34.0        M         O-
3         1004      SARAH      Brown    1957-12-04  34.0     Male         B+
4         1005    Michael      Jones    2009-02-19  78.0     MALE        AB+
..         ...        ...        ...           ...   ...      ...        ...
95        1096       Emma     Garcia    1979-04-02   NaN     MALE         B+
96        1097    william     Miller    1970-10-03  70.0        M        A +
97        1098     Olivia      Davis    1950-12-16  80.0        F         B-
98        1099      David  rodriguez           NaN  79.0        F        AB+
99        1100     Sophia   Martinez    15-08-1990  45.0     Male        AB+

   Admission_Date Discharge_Date  Diagnosis Temperature Blood_Pressure  \
0      2024/10/15            NaN        Flu       97.3F       151 / 88
1      2024-10-25     2024-11-03  Pneumonia        38.4         133/71
2      2025-07-09     2025-07-18   COVID-19        36.5          96/76
3      2024-11-25     2024-12-05   COVID-19        37.8         151/67
4      2024-12-19     2024-12-25   Migraine        38.0          98/85
..            ...            ...        ...         ...            ...
95     2025-02-11     2025-02-18   Diabetis        38.8         136/99
96     2025-11-06     2025-11-01        Flu         NaN        153/100
97     2024-10-30     2024-11-07   Migraine        36.8        146/108
98     2024/10/15     2024-10-16   COVID-19        36.5          96/73
99            NaN            NaN        Flu        37.4       124 / 95

    Heart_Rate Insurance_Provider Bill_Amount
0         78.0                NaN        $566
1         68.0              Cigna     5876.33
2         78.0          BlueCross      7015.1
3         88.0          BLUECROSS     7574.35
4         91.0       UnitedHealth      965.92
..         ...                ...         ...
95        66.0                NaN     4712.14
96        78.0                NaN     9530.27
97        88.0          BlueCross     8626.78
98        66.0       UnitedHealth       $1313
99        93.0              aetna     9818.81

[100 rows x 15 columns]
✓ Whitespace cleaned

In [371]:
# ----------------------------------------------------------------
# BUG CATEGORY 4: CASE CONSISTENCY
# ----------------------------------------------------------------
print("\n4️⃣ Fixing case inconsistencies...")

# TODO: Standardize capitalization in First_Name, Last_Name, Gender, etc.
# HINT: Use .str.title(), .str.upper(), or .str.lower() as appropriate
# for individual column path
print(df_clean['First_Name'].dtype) #check data type
df_clean['First_Name']= df_clean['First_Name'].apply(lambda x: str(x).strip().title() if pd.notna(x) else '') #use function because we have na values 
print(df_clean['First_Name'].unique())
#found a blank '' in there so have to convert it into NA
df_clean['First_Name'].replace('', pd.NA, inplace=True)
print(df_clean['First_Name'].isna().sum()) # check how many NA have been converted
df_clean['First_Name'].fillna('Benjamin', inplace=True) #change them to 'Benjamin'
print(df_clean['First_Name'].unique()) #check if it has worked
print(df_clean['First_Name'].isna().sum()) #confirm with the sum of Na should return 0

#for Last name colum
df_clean['Last_Name']= df_clean['Last_Name'].apply(lambda x: str(x).strip().title() if pd.notna(x) else '')
print(df_clean['Last_Name'].unique())
#found a blank '' in there so have to convert it into NA
df_clean['Last_Name'].replace('', pd.NA, inplace=True)
print(df_clean['Last_Name'].isna().sum()) # check how many NA have been converted
df_clean['Last_Name'].fillna('Rogers', inplace=True) #change them to 'Rogers'
print(df_clean['Last_Name'].unique()) #check if it has worked
print(df_clean['Last_Name'].isna().sum()) #confirm with the sum of Na should return 0
#for gender column, we need to standardise aswell
print(df_clean['Gender'].dtype)
df_clean['Gender']= df_clean['Gender'].apply(lambda x: str(x).strip().lower() if pd.notna(x) else '')
df_clean['Gender']=df_clean['Gender'].apply(lambda x: 'Male' if x.startswith('m') else 'Female' if x.startswith('f') else 'Unknown') # for any un listed gender, we replace it with unknown
print(df_clean['Gender'].unique())

print("✓ Case consistency applied")

4️⃣ Fixing case inconsistencies...
object
['John' 'Mary' 'James' 'Sarah' 'Michael' 'Robert' 'William' 'Olivia'
 'David' 'Sophia' '' 'Emma']
2
['John' 'Mary' 'James' 'Sarah' 'Michael' 'Robert' 'William' 'Olivia'
 'David' 'Sophia' 'Benjamin' 'Emma']
0
['Smith' 'Johnson' 'Williams' 'Brown' 'Jones' 'Garcia' 'Miller' 'Davis' ''
 'Martinez' 'Rodriguez']
2
['Smith' 'Johnson' 'Williams' 'Brown' 'Jones' 'Garcia' 'Miller' 'Davis'
 'Rogers' 'Martinez' 'Rodriguez']
0
object
['Unknown' 'Male' 'Female']
✓ Case consistency applied

In [372]:
# ----------------------------------------------------------------
# BUG CATEGORY 5: DATE FORMAT ISSUES
# ----------------------------------------------------------------
print("\n5️⃣ Converting date columns...")

# TODO: Convert Date_of_Birth, Admission_Date, Discharge_Date to proper datetime
# HINT: Use pd.to_datetime() with errors='coerce'
#coverting DOB first
df_clean['Date_of_Birth'] = df_clean['Date_of_Birth'].astype(str).str.strip().str.replace('/','-', regex=True)   #the astype() converts the column into a string style then strip removes extra whitespaces

df_clean['Date_of_Birth']= pd.to_datetime(df_clean['Date_of_Birth'], errors='coerce') # pd.to_datetime() converts to date/time format
df_clean['Date_of_Birth'].fillna(df_clean['Date_of_Birth'].median().normalize(), inplace=True) #generate values for all NAs (my choice is median). the normarlize helps to remove the time after calculating the median date
print(df_clean['Date_of_Birth'])
#converting ADMISSION DATE 
#print(df_clean['Admission_Date'].head(20))
#print(df_clean['Admission_Date'].unique())
df_clean['Admission_Date'] = df_clean['Admission_Date'].astype(str).str.strip().str.replace('/', '-', regex=True) #standardize the date format(this gave me headache finding the actual cause of NaT)
df_clean['Admission_Date']= pd.to_datetime(df_clean['Admission_Date'], errors='coerce', infer_datetime_format=True)
df_clean['Admission_Date'].fillna(df_clean['Admission_Date'].median().normalize(), inplace=True)
print(df_clean['Admission_Date'])
#coverting DISCHARGE DATE
df_clean['Discharge_Date'] = df_clean['Discharge_Date'].astype(str).str.strip()
df_clean['Discharge_Date']= pd.to_datetime(df_clean['Discharge_Date'], errors='coerce')
df_clean['Discharge_Date'].fillna(df_clean['Discharge_Date'].median().normalize(), inplace=True)
print(df_clean['Discharge_Date'])
print("✓ Dates converted")

5️⃣ Converting date columns...
0    1975-08-21
1    1954-01-24
2    1975-04-08
3    1957-12-04
4    2009-02-19
        ...
95   1979-04-02
96   1970-10-03
97   1950-12-16
98   1975-08-21
99   1975-08-21
Name: Date_of_Birth, Length: 100, dtype: datetime64[ns]
0    2024-10-15
1    2024-10-25
2    2025-07-09
3    2024-11-25
4    2024-12-19
        ...
95   2025-02-11
96   2025-11-06
97   2024-10-30
98   2024-10-15
99   2025-03-01
Name: Admission_Date, Length: 100, dtype: datetime64[ns]
0    2025-03-08
1    2024-11-03
2    2025-07-18
3    2024-12-05
4    2024-12-25
        ...
95   2025-02-18
96   2025-11-01
97   2024-11-07
98   2024-10-16
99   2025-03-08
Name: Discharge_Date, Length: 100, dtype: datetime64[ns]
✓ Dates converted

In [373]:
# ----------------------------------------------------------------
# BUG CATEGORY 6: DATA TYPE CONVERSIONS
# ----------------------------------------------------------------
print("\n6️⃣ Fixing data types...")

# TODO: Convert Age, Heart_Rate to integers (handle strings first)
# HINT: First convert strings to numeric, then to int
#coverting colums to numeric
cols =['Age', 'Heart_Rate']
df_clean[cols]= df_clean[cols].apply(pd.to_numeric, errors='coerce')
#converting to intergers
df_clean[cols] = df_clean[cols].astype('Int64')


# TODO: Convert Bill_Amount to float (remove $ symbols first)
# HINT: Use .str.replace() to remove $ then convert to float
df_clean['Bill_Amount']= df_clean['Bill_Amount'].astype(str).str.replace('$', '')
#coverting to float
df_clean['Bill_Amount'] = df_clean['Bill_Amount'].astype(float)
# generating values for NAs
df_clean['Bill_Amount'].fillna(df_clean['Bill_Amount'].mode(), inplace=True)
print(df_clean['Bill_Amount'].isna().sum) #check if it has worked, should return 0
print(df_clean['Bill_Amount'].unique())

print("✓ Data types corrected")
df_clean

6️⃣ Fixing data types...
<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Bill_Amount, Length: 100, dtype: bool>
[ 566.   5876.33 7015.1  7574.35  965.92 6260.86 5218.91 9089.48 3218.84
 8089.17 6267.12 3847.05 6547.87 6398.47 1620.   6468.36 9082.34 6640.24
 3434.86 4687.82 -693.   3966.18 1748.41 9141.46 3603.83 3012.36 4447.28
 2407.55 4918.   8826.38 3975.65 5267.05 3089.01 2063.17 9183.47 9469.78
 9690.15 3303.84 8768.77 8140.21 -579.   9647.49 1653.   7664.44 2643.34
 6925.08 6906.86 4275.41 8534.57 5794.47 5148.8  1357.88 4248.46 1674.09
 4001.56 2647.   6053.32 8312.96 9432.77 -210.   6910.95 4979.03 6385.7
 9460.11 3616.06 6295.78 6652.7  6536.34 4910.54 2975.   6667.77 1608.42
  930.79  853.52 9961.31 1603.14 2730.6  5606.69 -497.   4809.62 6869.62
 7559.83 4925.   4481.7  7551.56 1967.97 4441.4  1440.71 4377.1  9539.45
  810.8  4020.03 4712.14 9530.27 8626.78 1313.   9818.81]
✓ Data types corrected

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,1975-08-21,45,Unknown,A +,2024-10-15,2025-03-08,Flu,97.3F,151 / 88,78,NaN,566.00
1,1002,Mary,Johnson,1954-01-24,26,Male,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68,Cigna,5876.33
2,1003,James,Williams,1975-04-08,34,Male,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78,BlueCross,7015.10
3,1004,Sarah,Brown,1957-12-04,34,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88,BLUECROSS,7574.35
4,1005,Michael,Jones,2009-02-19,78,Male,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91,UnitedHealth,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,<NA>,Male,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66,NaN,4712.14
96,1097,William,Miller,1970-10-03,70,Male,A +,2025-11-06,2025-11-01,Flu,NaN,153/100,78,NaN,9530.27
97,1098,Olivia,Davis,1950-12-16,80,Female,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88,BlueCross,8626.78
98,1099,David,Rodriguez,1975-08-21,79,Female,AB+,2024-10-15,2024-10-16,COVID-19,36.5,96/73,66,UnitedHealth,1313.00
99,1100,Sophia,Martinez,1975-08-21,45,Male,AB+,2025-03-01,2025-03-08,Flu,37.4,124 / 95,93,aetna,9818.81

In [374]:
# ----------------------------------------------------------------
# BUG CATEGORY 7: INVALID VALUES
# ----------------------------------------------------------------
print("\n7️⃣ Handling invalid values...")

# TODO: Fix negative ages, impossible ages (>120), negative bill amounts
# HINT: Use conditional replacement or set to NaN
#setting  invalids to NaN
df_clean.loc[(df_clean['Age'] < 0)| (df_clean['Age'] > 120), 'Age'] = pd.NA
#filling all nA vales with the median age(or can be any value you want)
df_clean['Age'] = df["Age"].fillna(df['Age'].median())


# TODO: Fix heart rates outside normal range (30-200)
#setting abnormal values to NA
df_clean.loc[(df_clean['Heart_Rate'] < 30)| (df_clean['Heart_Rate'] > 200), 'Heart_Rate'] = pd.NA
#filling all nA vales with the median Heart_Rate(or can be any value you want)
df_clean['Heart_Rate'] = df["Heart_Rate"].fillna(df['Heart_Rate'].median())

# TODO: Fix impossible temperatures (>42°C or <30°C)
#converting temperature column to string first
df_clean['Temperature'].replace('', np.nan, inplace = True) #replace blanks first
df_clean['Temperature']= df_clean['Temperature'].astype(str).str.strip() # also remove extra spaces
#create a mask for farenheit values and 'normal'
mask_F = df_clean['Temperature'].str.endswith(('F', 'f'))
mask_N = df_clean['Temperature'].str.lower()=='normal'
#convert these to celsius
df_clean.loc[mask_F, 'Temperature'] = ((df_clean.loc[mask_F, 'Temperature'].str.rstrip('Ff').astype(float)-32)*5/9) 
df_clean.loc[mask_N, 'Temperature'] = 37.0 

#now convert to float and round off to 1 decimal place
df_clean.loc[mask_F, 'Temperature']= pd.to_numeric(df_clean.loc[mask_F, 'Temperature'], errors='coerce').round(1)
df_clean.loc[mask_N, 'Temperature']= pd.to_numeric(df_clean.loc[mask_N, 'Temperature'], errors='coerce')
df_clean['Temperature']= pd.to_numeric(df_clean['Temperature'],errors='coerce')
                    
#setting imposible values to NA
df_clean.loc[(df_clean['Temperature'] < 30)| (df_clean['Temperature'] > 42), 'Temperature'] = np.nan
#filling all nA vales with the median temperature(or can be any value you want)
print(df_clean['Temperature'].isna().sum)
df_clean['Temperature'].fillna(df_clean['Temperature'].median(), inplace=True)
# check to see if values have changed
print(df_clean.loc[0:50, 'Temperature'])
print(df_clean.loc[50:101, 'Temperature'])

print("✓ Invalid values handled")
df_clean

7️⃣ Handling invalid values...
<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
      ...
95    False
96     True
97    False
98    False
99    False
Name: Temperature, Length: 100, dtype: bool>
0     36.3
1     38.4
2     36.5
3     37.8
4     38.0
5     37.8
6     37.6
7     39.2
8     37.9
9     37.0
10    37.0
11    38.1
12    38.5
13    37.5
14    39.3
15    38.8
16    37.9
17    37.0
18    39.0
19    38.3
20    37.6
21    37.5
22    37.2
23    39.3
24    37.6
25    37.3
26    37.1
27    38.8
28    38.2
29    38.5
30    37.5
31    38.0
32    37.5
33    38.0
34    37.0
35    37.6
36    37.3
37    37.3
38    38.3
39    38.1
40    37.6
41    38.2
42    38.0
43    37.1
44    37.2
45    37.7
46    38.2
47    37.2
48    37.6
49    37.9
50    38.6
Name: Temperature, dtype: float64
50    38.6
51    37.0
52    37.1
53    36.6
54    37.4
55    37.7
56    37.2
57    38.5
58    37.6
59    38.2
60    37.6
61    37.5
62    39.5
63    38.2
64    37.6
65    37.1
66    37.4
67    37.2
68    37.0
69    38.7
70    37.4
71    38.7
72    37.6
73    39.4
74    38.6
75    37.1
76    38.7
77    37.3
78    37.4
79    38.8
80    37.6
81    38.3
82    39.4
83    39.0
84    37.4
85    37.0
86    37.6
87    37.4
88    38.6
89    36.9
90    36.6
91    36.2
92    37.4
93    39.3
94    38.4
95    38.8
96    37.6
97    36.8
98    36.5
99    37.4
Name: Temperature, dtype: float64
✓ Invalid values handled

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,1975-08-21,45.0,Unknown,A +,2024-10-15,2025-03-08,Flu,36.3,151 / 88,78.0,NaN,566.00
1,1002,Mary,Johnson,1954-01-24,26.0,Male,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003,James,Williams,1975-04-08,34.0,Male,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78.0,BlueCross,7015.10
3,1004,Sarah,Brown,1957-12-04,34.0,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88.0,BLUECROSS,7574.35
4,1005,Michael,Jones,2009-02-19,78.0,Male,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,UnitedHealth,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,45.0,Male,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66.0,NaN,4712.14
96,1097,William,Miller,1970-10-03,70.0,Male,A +,2025-11-06,2025-11-01,Flu,37.6,153/100,78.0,NaN,9530.27
97,1098,Olivia,Davis,1950-12-16,80.0,Female,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88.0,BlueCross,8626.78
98,1099,David,Rodriguez,1975-08-21,79.0,Female,AB+,2024-10-15,2024-10-16,COVID-19,36.5,96/73,66.0,UnitedHealth,1313.00
99,1100,Sophia,Martinez,1975-08-21,45.0,Male,AB+,2025-03-01,2025-03-08,Flu,37.4,124 / 95,93.0,aetna,9818.81

In [375]:
# ----------------------------------------------------------------
# BUG CATEGORY 8: BLOOD TYPE ISSUES
# ----------------------------------------------------------------
print("\n8️⃣ Cleaning Blood Types...")

# TODO: Fix '0+' to 'O+', remove extra spaces, handle invalid blood types
# HINT: Use .replace() or .str.replace()
#find discrepancy in blood groups
print(df_clean.loc[:, 'Blood_Type']) # for viewing the whole dataset but only the column of bloodtype
df_clean['Blood_Type'].unique() # for finding the unique values in the column of dataset
#replace / make similar the values with discrepancies
df_clean['Blood_Type'].replace({'A +': 'A+', '0+':'O+', 'XY+':'AB+'}, inplace=True)
df_clean['Blood_Type'].unique() #check to see if it has worked
#now handle the blanks
print(df_clean['Blood_Type'].isna().sum()) #check and confirm how many blanks you have
df_clean['Blood_Type'].fillna(df_clean['Blood_Type'].mode()[0], inplace=True)
df_clean['Blood_Type'].unique() #check to see if it has worked
print("✓ Blood types cleaned")
df_clean

8️⃣ Cleaning Blood Types...
0     A +
1      A+
2      O-
3      B+
4     AB+
     ...
95     B+
96    A +
97     B-
98    AB+
99    AB+
Name: Blood_Type, Length: 100, dtype: object
2
✓ Blood types cleaned

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,1975-08-21,45.0,Unknown,A+,2024-10-15,2025-03-08,Flu,36.3,151 / 88,78.0,NaN,566.00
1,1002,Mary,Johnson,1954-01-24,26.0,Male,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003,James,Williams,1975-04-08,34.0,Male,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78.0,BlueCross,7015.10
3,1004,Sarah,Brown,1957-12-04,34.0,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88.0,BLUECROSS,7574.35
4,1005,Michael,Jones,2009-02-19,78.0,Male,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,UnitedHealth,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,45.0,Male,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66.0,NaN,4712.14
96,1097,William,Miller,1970-10-03,70.0,Male,A+,2025-11-06,2025-11-01,Flu,37.6,153/100,78.0,NaN,9530.27
97,1098,Olivia,Davis,1950-12-16,80.0,Female,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88.0,BlueCross,8626.78
98,1099,David,Rodriguez,1975-08-21,79.0,Female,AB+,2024-10-15,2024-10-16,COVID-19,36.5,96/73,66.0,UnitedHealth,1313.00
99,1100,Sophia,Martinez,1975-08-21,45.0,Male,AB+,2025-03-01,2025-03-08,Flu,37.4,124 / 95,93.0,aetna,9818.81

In [376]:
# ----------------------------------------------------------------
# BUG CATEGORY 9: TEMPERATURE UNITS
# ----------------------------------------------------------------
print("\n9️⃣ Standardizing temperature units...")

# TODO: Convert all temperatures to Celsius (remove 'F', convert if needed)
# HINT: Check for 'F' in string, use formula: (F - 32) * 5/9


#done in previous sections

print("✓ Temperatures standardized")

9️⃣ Standardizing temperature units...
✓ Temperatures standardized

In [377]:
# ----------------------------------------------------------------
# BUG CATEGORY 10: BLOOD PRESSURE FORMAT
# ----------------------------------------------------------------
print("\n🔟 Standardizing blood pressure format...")

# TODO: Make all blood pressure values use '/' separator
# HINT: Replace ' / ' and '-' with '/'
#start with finding out the discrepancies
print(df_clean['Blood_Pressure'].unique())
df_clean['Blood_Pressure']= df_clean['Blood_Pressure'].astype(str).str.strip().str.lower()
#now change to '/' for all and also change normal to the most common value
df_clean['Blood_Pressure'].replace({' / ': '/', '-':'/', 'normal': '120/80'}, regex=True, inplace=True)
print(df_clean['Blood_Pressure'].unique()) #check to see if it has worked
print(df_clean.loc[0: 50, 'Blood_Pressure'])
#generate values for NAs
df_clean['Blood_Pressure'].fillna(df_clean['Blood_Pressure'].mode()[0], inplace=True)
print(df_clean['Blood_Pressure'].isna().sum()) # check to see if it has worked
print("✓ Blood pressure standardized")
print(df_clean.loc[0:50, 'Blood_Pressure'])
df_clean

🔟 Standardizing blood pressure format...
['151 / 88' '133/71' '96/76' '151/67' '98/85' '152/64' '163/100' '177/63'
 '109/69' '162 / 120' '128/65' '121/67' '161/108' '143/98' '166/110'
 '169-74' '156/84' '147/118' '146 / 79' '165/87' '129/96' nan '168/107'
 '102/120' '116/100' '117/76' 'normal' '110 / 75' '112/95' '99/70' '90-86'
 '147/104' '166/90' '127/62' '119/78' '180/78' '179 / 115' '148/64'
 '177/74' '123/110' '170/97' '174/111' '104/94' '118/101' '109 / 118'
 '124/112' '108/64' '97/70' '129/98' '162/118' '126/88' '178/79'
 '179 / 85' '124/92' '159/91' '146/65' '166/62' '145/107' '131-98'
 '122/61' '101/74' '176 / 113' '163/97' '92/108' '176/112' '124/96'
 '95/108' '112/90' '156/101' '146/118' '125 / 71' '164/87' '171/112'
 '152-65' '150/82' '142/81' '103/114' '110/81' '142 / 104' '153/78'
 '174/120' '160/62' '148/65' '130/76' '131/67' '141/115' '155 / 112'
 '90/102' '159/89' '142/63' '114/93' '136/99' '153/100' '146/108' '96/73'
 '124 / 95']
['151/88' '133/71' '96/76' '151/67' '98/85' '152/64' '163/100' '177/63'
 '109/69' '162/120' '128/65' '121/67' '161/108' '143/98' '166/110'
 '169/74' '156/84' '147/118' '146/79' '165/87' '129/96' 'nan' '168/107'
 '102/120' '116/100' '117/76' '120/80' '110/75' '112/95' '99/70' '90/86'
 '147/104' '166/90' '127/62' '119/78' '180/78' '179/115' '148/64' '177/74'
 '123/110' '170/97' '174/111' '104/94' '118/101' '109/118' '124/112'
 '108/64' '97/70' '129/98' '162/118' '126/88' '178/79' '179/85' '124/92'
 '159/91' '146/65' '166/62' '145/107' '131/98' '122/61' '101/74' '176/113'
 '163/97' '92/108' '176/112' '124/96' '95/108' '112/90' '156/101'
 '146/118' '125/71' '164/87' '171/112' '152/65' '150/82' '142/81'
 '103/114' '110/81' '142/104' '153/78' '174/120' '160/62' '148/65'
 '130/76' '131/67' '141/115' '155/112' '90/102' '159/89' '142/63' '114/93'
 '136/99' '153/100' '146/108' '96/73' '124/95']
0      151/88
1      133/71
2       96/76
3      151/67
4       98/85
5      152/64
6     163/100
7      177/63
8      109/69
9     162/120
10     128/65
11     121/67
12    161/108
13     143/98
14    166/110
15     169/74
16     156/84
17    147/118
18     146/79
19     165/87
20     129/96
21        nan
22    168/107
23    102/120
24    116/100
25     117/76
26     120/80
27     110/75
28     112/95
29      99/70
30      90/86
31    147/104
32     166/90
33     127/62
34     119/78
35     180/78
36    179/115
37     148/64
38     177/74
39    123/110
40     170/97
41    174/111
42        nan
43     104/94
44    118/101
45    109/118
46    124/112
47     108/64
48      97/70
49     129/98
50    162/118
Name: Blood_Pressure, dtype: object
0
✓ Blood pressure standardized
0      151/88
1      133/71
2       96/76
3      151/67
4       98/85
5      152/64
6     163/100
7      177/63
8      109/69
9     162/120
10     128/65
11     121/67
12    161/108
13     143/98
14    166/110
15     169/74
16     156/84
17    147/118
18     146/79
19     165/87
20     129/96
21        nan
22    168/107
23    102/120
24    116/100
25     117/76
26     120/80
27     110/75
28     112/95
29      99/70
30      90/86
31    147/104
32     166/90
33     127/62
34     119/78
35     180/78
36    179/115
37     148/64
38     177/74
39    123/110
40     170/97
41    174/111
42        nan
43     104/94
44    118/101
45    109/118
46    124/112
47     108/64
48      97/70
49     129/98
50    162/118
Name: Blood_Pressure, dtype: object

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,1975-08-21,45.0,Unknown,A+,2024-10-15,2025-03-08,Flu,36.3,151/88,78.0,NaN,566.00
1,1002,Mary,Johnson,1954-01-24,26.0,Male,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003,James,Williams,1975-04-08,34.0,Male,O-,2025-07-09,2025-07-18,COVID-19,36.5,96/76,78.0,BlueCross,7015.10
3,1004,Sarah,Brown,1957-12-04,34.0,Male,B+,2024-11-25,2024-12-05,COVID-19,37.8,151/67,88.0,BLUECROSS,7574.35
4,1005,Michael,Jones,2009-02-19,78.0,Male,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,UnitedHealth,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,45.0,Male,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66.0,NaN,4712.14
96,1097,William,Miller,1970-10-03,70.0,Male,A+,2025-11-06,2025-11-01,Flu,37.6,153/100,78.0,NaN,9530.27
97,1098,Olivia,Davis,1950-12-16,80.0,Female,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88.0,BlueCross,8626.78
98,1099,David,Rodriguez,1975-08-21,79.0,Female,AB+,2024-10-15,2024-10-16,COVID-19,36.5,96/73,66.0,UnitedHealth,1313.00
99,1100,Sophia,Martinez,1975-08-21,45.0,Male,AB+,2025-03-01,2025-03-08,Flu,37.4,124/95,93.0,aetna,9818.81

In [378]:
# ----------------------------------------------------------------
# BUG CATEGORY 11: INSURANCE PROVIDER CONSISTENCY
# ----------------------------------------------------------------
print("\n1️⃣1️⃣ Standardizing insurance providers...")

# TODO: Make all provider names consistent (e.g., all 'BlueCross' or all 'Aetna')
# HINT: Use .str.lower() then .str.title() or create a mapping
#check items in insurance column
print(df_clean['Insurance_Provider'].unique())
#create a map basing on the unique values
map_IP={
    'CIGNA': 'Cigna',
    'BLUECROSS': 'BlueCross',
    'blue cross': 'BlueCross',
    'UnitedHealth': 'United Health',
    'aetna': 'Aetna'

}
#Use map to standardise
df_clean['Insurance_Provider']= df_clean['Insurance_Provider'].map(map_IP).fillna(df_clean['Insurance_Provider']) #the fillna allows the map to skip values that arent in the map dictionary
print(df_clean['Insurance_Provider'].unique())
#work on the NA values
df_clean['Insurance_Provider'] = df_clean['Insurance_Provider'].fillna(df_clean['Insurance_Provider'].mode()[0]) 
print(df_clean.loc[0:50, 'Insurance_Provider'])  #confirm that it has worked
print("✓ Insurance providers standardized")

1️⃣1️⃣ Standardizing insurance providers...
[nan 'Cigna' 'BlueCross' 'BLUECROSS' 'UnitedHealth' 'blue cross' 'aetna'
 'United Health' 'Medicare' 'CIGNA' 'Aetna']
[nan 'Cigna' 'BlueCross' 'United Health' 'Aetna' 'Medicare']
0         BlueCross
1             Cigna
2         BlueCross
3         BlueCross
4     United Health
5         BlueCross
6         BlueCross
7             Cigna
8             Aetna
9     United Health
10         Medicare
11    United Health
12        BlueCross
13    United Health
14            Cigna
15    United Health
16        BlueCross
17    United Health
18            Cigna
19        BlueCross
20            Cigna
21        BlueCross
22         Medicare
23        BlueCross
24            Aetna
25            Aetna
26            Aetna
27        BlueCross
28    United Health
29        BlueCross
30        BlueCross
31            Cigna
32        BlueCross
33        BlueCross
34            Aetna
35        BlueCross
36        BlueCross
37    United Health
38        BlueCross
39        BlueCross
40            Aetna
41    United Health
42    United Health
43    United Health
44        BlueCross
45            Aetna
46            Cigna
47    United Health
48        BlueCross
49         Medicare
50        BlueCross
Name: Insurance_Provider, dtype: object
✓ Insurance providers standardized

In [379]:
# ----------------------------------------------------------------
# BUG CATEGORY 12: DIAGNOSIS CLEANUP
# ----------------------------------------------------------------
print("\n1️⃣2️⃣ Cleaning diagnosis field...")

# TODO: Strip whitespace, fix typos (e.g., 'Diabetis' -> 'Diabetes')
# HINT: Use .str.strip() and .replace()
#start with removing white spaces
df_clean['Diagnosis'] = df_clean['Diagnosis'].str.title().str.strip()
#check for spellings
df_clean['Diagnosis'].unique()
df_clean['Diagnosis'].replace({'diabetis': 'Diabetes'}, inplace=True) #replace any that is incorrect
print(df_clean.loc[0:50, 'Diagnosis']) #check to see if has worked

#print("✓ Diagnosis cleaned")

1️⃣2️⃣ Cleaning diagnosis field...
0              Flu
1        Pneumonia
2         Covid-19
3         Covid-19
4         Migraine
5         Migraine
6          Anxiety
7       Bronchitis
8         Fracture
9       Bronchitis
10       Pneumonia
11        Covid-19
12        Fracture
13    Hypertension
14        Covid-19
15             Flu
16        Covid-19
17          Asthma
18        Fracture
19        Diabetis
20          Asthma
21         Anxiety
22        Migraine
23    Hypertension
24        Covid-19
25         Anxiety
26         Anxiety
27    Hypertension
28        Diabetes
29        Covid-19
30          Asthma
31        Fracture
32          Asthma
33    Hypertension
34       Pneumonia
35        Covid-19
36             Flu
37      Bronchitis
38        Diabetis
39        Fracture
40             Flu
41             Flu
42        Covid-19
43       Pneumonia
44        Covid-19
45       Pneumonia
46        Diabetes
47        Fracture
48    Hypertension
49        Migraine
50    Hypertension
Name: Diagnosis, dtype: object

In [380]:
# ----------------------------------------------------------------
# BUG CATEGORY 13: LOGICAL INCONSISTENCIES
# ----------------------------------------------------------------
print("\n1️⃣3️⃣ Checking logical consistency...")

# TODO: Ensure Discharge_Date is after Admission_Date
# HINT: Compare the two date columns
# check if Admission date is before discarge date
print(df_clean[df_clean['Admission_Date'] > df_clean['Discharge_Date']])
#for any discharge before admission, we swap the dates
date_mask = df_clean['Admission_Date']> df_clean['Discharge_Date']
df_clean.loc[date_mask, ['Admission_Date', 'Discharge_Date']]= df_clean.loc[date_mask, ['Discharge_Date', 'Admission_Date']].values
print(df_clean[df_clean['Admission_Date'] > df_clean['Discharge_Date']]) # confirm if it has worked, it should return an empty value


# TODO: Calculate proper age from Date_of_Birth
# age will be calculated at the time of admission
df_clean.loc[df_clean['Date_of_Birth'].notna() & df_clean['Admission_Date'].notna(),'Age'] = (df_clean['Admission_Date']- df_clean['Date_of_Birth']).dt.days //365

#print("✓ Logical consistency checked")
df_clean

1️⃣3️⃣ Checking logical consistency...
    Patient_ID First_Name  Last_Name Date_of_Birth   Age  Gender Blood_Type  \
8         1009      David     Rogers    2004-10-01  72.0  Female         O-
10        1011       John      Smith    2009-07-08  43.0    Male         O-
16        1017    William     Miller    1994-06-09  84.0    Male        AB+
20        1021       John      Smith    1975-08-21  33.0    Male         B+
21        1022       Mary    Johnson    1975-08-21  49.0  Female         B+
24        1025    Michael      Jones    1945-12-15  26.0  Female         A+
32        1033      James   Williams    1969-05-03  25.0  Female         B+
48        1049      David  Rodriguez    2011-04-22  78.0  Female         A+
50        1051       John      Smith    1981-01-08  78.0  Female        AB+
56        1057    William     Miller    1975-08-21  30.0  Female        AB+
63        1064      Sarah      Brown    1975-08-21  24.0    Male         O+
64        1065    Michael      Jones    1991-06-08  30.0  Female         A+
80        1081       John      Smith    1975-08-21  41.0  Female         O-
88        1089      David  Rodriguez    1975-08-21  24.0    Male         O+
96        1097    William     Miller    1970-10-03  70.0    Male         A+

   Admission_Date Discharge_Date     Diagnosis  Temperature Blood_Pressure  \
8      2025-10-06     2025-10-01      Fracture         37.9         109/69
10     2025-05-04     2025-03-08     Pneumonia         37.0         128/65
16     2025-11-06     2025-11-01      Covid-19         37.9         156/84
20     2025-04-25     2025-03-08        Asthma         37.6         129/96
21     2025-03-01     2024-10-18       Anxiety         37.5            nan
24     2025-02-22     2025-02-17      Covid-19         37.6        116/100
32     2025-11-06     2025-11-01        Asthma         37.5         166/90
48     2025-11-06     2025-11-01  Hypertension         37.6          97/70
50     2025-06-27     2025-03-08  Hypertension         38.6        162/118
56     2024-10-15     2024-10-10    Bronchitis         37.2         159/91
63     2025-03-01     2024-10-19        Asthma         38.2        176/113
64     2025-11-06     2025-11-01      Fracture         37.6         163/97
80     2025-11-06     2025-03-08  Hypertension         37.6         110/81
88     2025-09-11     2025-09-06    Bronchitis         38.6         131/67
96     2025-11-06     2025-11-01           Flu         37.6        153/100

    Heart_Rate Insurance_Provider  Bill_Amount
8         98.0              Aetna      3218.84
10        70.0           Medicare      6267.12
16        86.0          BlueCross      9082.34
20        67.0              Cigna      -693.00
21        89.0          BlueCross      3966.18
24        78.0              Aetna      3603.83
32        90.0          BlueCross      3089.01
48        78.0          BlueCross      8534.57
50        92.0          BlueCross      5148.80
56        80.0           Medicare      2647.00
63        94.0              Cigna      6385.70
64        90.0          BlueCross      9460.11
80        62.0          BlueCross      -497.00
88        62.0              Aetna      4441.40
96        78.0          BlueCross      9530.27
Empty DataFrame
Columns: [Patient_ID, First_Name, Last_Name, Date_of_Birth, Age, Gender, Blood_Type, Admission_Date, Discharge_Date, Diagnosis, Temperature, Blood_Pressure, Heart_Rate, Insurance_Provider, Bill_Amount]
Index: []

,Patient_ID,First_Name,Last_Name,Date_of_Birth,Age,Gender,Blood_Type,Admission_Date,Discharge_Date,Diagnosis,Temperature,Blood_Pressure,Heart_Rate,Insurance_Provider,Bill_Amount
0,1001,John,Smith,1975-08-21,49.0,Unknown,A+,2024-10-15,2025-03-08,Flu,36.3,151/88,78.0,BlueCross,566.00
1,1002,Mary,Johnson,1954-01-24,70.0,Male,A+,2024-10-25,2024-11-03,Pneumonia,38.4,133/71,68.0,Cigna,5876.33
2,1003,James,Williams,1975-04-08,50.0,Male,O-,2025-07-09,2025-07-18,Covid-19,36.5,96/76,78.0,BlueCross,7015.10
3,1004,Sarah,Brown,1957-12-04,67.0,Male,B+,2024-11-25,2024-12-05,Covid-19,37.8,151/67,88.0,BlueCross,7574.35
4,1005,Michael,Jones,2009-02-19,15.0,Male,AB+,2024-12-19,2024-12-25,Migraine,38.0,98/85,91.0,United Health,965.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Emma,Garcia,1979-04-02,45.0,Male,B+,2025-02-11,2025-02-18,Diabetis,38.8,136/99,66.0,BlueCross,4712.14
96,1097,William,Miller,1970-10-03,55.0,Male,A+,2025-11-01,2025-11-06,Flu,37.6,153/100,78.0,BlueCross,9530.27
97,1098,Olivia,Davis,1950-12-16,73.0,Female,B-,2024-10-30,2024-11-07,Migraine,36.8,146/108,88.0,BlueCross,8626.78
98,1099,David,Rodriguez,1975-08-21,49.0,Female,AB+,2024-10-15,2024-10-16,Covid-19,36.5,96/73,66.0,United Health,1313.00
99,1100,Sophia,Martinez,1975-08-21,49.0,Male,AB+,2025-03-01,2025-03-08,Flu,37.4,124/95,93.0,Aetna,9818.81

In [381]:
# ================================================================
# STEP 14: FINAL VALIDATION
# ================================================================

print("\n" + "="*70)
print("🏁 CLEANING COMPLETE - FINAL VALIDATION")
print("="*70)

# Check missing values after cleaning
print("\n❓ Missing Values After Cleaning:")
print(df_clean.isnull().sum())

# Check data types
print("\n📊 Data Types After Cleaning:")
print(df_clean.dtypes)

# Display sample of cleaned data
print("\n✨ Sample of Cleaned Data:")
print(df_clean.head(10))

======================================================================
🏁 CLEANING COMPLETE - FINAL VALIDATION
======================================================================

❓ Missing Values After Cleaning:
Patient_ID            0
First_Name            0
Last_Name             0
Date_of_Birth         0
Age                   0
Gender                0
Blood_Type            0
Admission_Date        0
Discharge_Date        0
Diagnosis             0
Temperature           0
Blood_Pressure        0
Heart_Rate            0
Insurance_Provider    0
Bill_Amount           0
dtype: int64

📊 Data Types After Cleaning:
Patient_ID                     int64
First_Name                    object
Last_Name                     object
Date_of_Birth         datetime64[ns]
Age                          float64
Gender                        object
Blood_Type                    object
Admission_Date        datetime64[ns]
Discharge_Date        datetime64[ns]
Diagnosis                     object
Temperature                  float64
Blood_Pressure                object
Heart_Rate                   float64
Insurance_Provider            object
Bill_Amount                  float64
dtype: object

✨ Sample of Cleaned Data:
   Patient_ID First_Name Last_Name Date_of_Birth   Age   Gender Blood_Type  \
0        1001       John     Smith    1975-08-21  49.0  Unknown         A+
1        1002       Mary   Johnson    1954-01-24  70.0     Male         A+
2        1003      James  Williams    1975-04-08  50.0     Male         O-
3        1004      Sarah     Brown    1957-12-04  67.0     Male         B+
4        1005    Michael     Jones    2009-02-19  15.0     Male        AB+
5        1006     Robert    Garcia    1994-01-01  31.0     Male         B+
6        1007    William    Miller    1951-04-08  73.0     Male         A+
7        1008     Olivia     Davis    1975-08-21  49.0     Male         O+
8        1009      David    Rogers    2004-10-01  21.0   Female         O-
9        1010     Sophia  Martinez    2011-04-23  13.0     Male         A+

  Admission_Date Discharge_Date   Diagnosis  Temperature Blood_Pressure  \
0     2024-10-15     2025-03-08         Flu         36.3         151/88
1     2024-10-25     2024-11-03   Pneumonia         38.4         133/71
2     2025-07-09     2025-07-18    Covid-19         36.5          96/76
3     2024-11-25     2024-12-05    Covid-19         37.8         151/67
4     2024-12-19     2024-12-25    Migraine         38.0          98/85
5     2025-05-05     2025-05-18    Migraine         37.8         152/64
6     2025-03-13     2025-03-21     Anxiety         37.6        163/100
7     2024-12-30     2025-01-09  Bronchitis         39.2         177/63
8     2025-10-01     2025-10-06    Fracture         37.9         109/69
9     2025-03-01     2025-03-08  Bronchitis         37.0        162/120

   Heart_Rate Insurance_Provider  Bill_Amount
0        78.0          BlueCross       566.00
1        68.0              Cigna      5876.33
2        78.0          BlueCross      7015.10
3        88.0          BlueCross      7574.35
4        91.0      United Health       965.92
5        67.0          BlueCross      6260.86
6        61.0          BlueCross      5218.91
7       100.0              Cigna      9089.48
8        98.0              Aetna      3218.84
9        75.0      United Health      8089.17

In [382]:
# ================================================================
# STEP 15: BASIC ANALYSIS (Prove your cleaning worked!)
# ================================================================

print("\n" + "="*70)
print("📊 BASIC ANALYSIS ON CLEANED DATA")
print("="*70)

# TODO: Calculate and display:
# 1. Average age of patients
print(f"\nthe average age of patients is, {df_clean['Age'].mean()}")
# 2. Most common diagnosis
print(f"\nthe most common diagnosis is, {df_clean['Diagnosis'].mode()[0]}")
# 3. Average bill amount
print(f"\nthe average bill is, {df_clean['Bill_Amount'].mean().round(2)}")
# 4. Gender distribution
print(f"\nthe gender distribution is as follows, {df_clean['Gender'].value_counts()}")
# 5. Most common blood type
print(f"\nthe most common blood group is, {df_clean['Blood_Type'].mode()[0]}")

======================================================================
📊 BASIC ANALYSIS ON CLEANED DATA
======================================================================

the average age of patients is, 47.19

the most common diagnosis is, Anxiety

the average bill is, 5100.5

the gender distribution is as follows, Gender
Male       52
Female     41
Unknown     7
Name: count, dtype: int64

the most common blood group is, A+

In [383]:
# ================================================================
# STEP 16: SAVE YOUR CLEANED DATA
# ================================================================

# TODO: Save the cleaned dataset
df_clean.to_csv('cleaned_patient_records.csv', index=False)
print("\n✅ Cleaned data saved to 'cleaned_patient_records.csv'")

print("\n" + "="*70)
print("🎉 CHALLENGE COMPLETE!")
print("="*70)
print("\nSubmit your notebook to instructor for scoring.")
print("Remember to document what bugs you found and how you fixed them!")

✅ Cleaned data saved to 'cleaned_patient_records.csv'

======================================================================
🎉 CHALLENGE COMPLETE!
======================================================================

Submit your notebook to instructor for scoring.
Remember to document what bugs you found and how you fixed them!